name: "Keyboard Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/config.yml
    - config/**

jobs:
  lily58-build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: config/lily58.yaml
      config_path: config
      archive_name: lily58-firmware
        
  lily58-store:
    if: always()
    needs: lily58-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        path: config
        merge-multiple: true
    - uses: sylvanld/action-storage@v1
      with:
        src: config
        dst: ./
        storage-branch: main
